### ISSUE TITLE
Output the ec config? And a bug.

### ISSUE THREAD

**Issue by cyberpunkbln** [zuyan9/RLECViewer#2]
Hello,

nice little software. I have not an clevo, i have an german copy of an clevo, but this programm is the first that correct fetch the ec adresses for controlling.

Give it a chance that i can dump the correct values for the ec adresses? In your code i see you determine the adresse on the fly.

And a short bug: The Fans goes on and off when it reaches the temp limits. I think your software correct on the fly the fan speed but the internal ec/bios correct it after your software has correct it?

thx

**Comment by Brainiarc7** [comment]
Hello there,

If its' fan control you're after, use Tuxedo's facility instead. Mentioned on this issue: https://github.com/hirschmann/nbfc/issues/385

**Comment by cyberpunkbln** [comment]
Hello,

thx for this link, very usefull. Unfortunately not for Windows 10 but in den source-code all important ec-registern and calls are documented.

C-Coding was a few years ago;), now i must look to find an Manual how i can controll an Embedded Controller with Rust without use unsafe c/c++ code, Pure Rust;).

thx
